# Generated by Django 5.2.15 on 2026-08-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_workflow_current_handler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='workflow_current_handler',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_evaluator',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_executor',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_history',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_returned_from',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_returned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_reviewer',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_splitter',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='workflow_stage',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='backend_path',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='frontend_path',
        ),
    ]
